### ISSUE TITLE
试用建议

### ISSUE THREAD

**Issue by hd2y** [newbe36524/Amazing-Favorites#1]
学习一下，顺便提点建议：
1. 希望支持历史记录的搜索，如果可以实现的话。
2. 网站的 favicon 能不能显示到搜索列表里，更直观一些，另外建议给个序号。
3. 搜索结果能用“↑”“↓”选择，回车直接 New Tag。
4. Alt + 数字打开有点问题，如果没有选择送掉焦点会离开输入框，希望没有选择焦点能回去。

另外，笔芯。（ε=ε=ε=┏(゜ロ゜;)┛

**Comment by newbe36524** [comment]
1. 暂不考虑
2. favicon 采纳，已实现。序号，采纳，已实现
3. 采纳，已实现
4. 暂无解决方案
