### ISSUE TITLE
立刻,马上,loading完成!

### ISSUE THREAD

**Issue by NMSAzulX** [newbe36524/Amazing-Favorites#54]
在不方便的时候,在搞一些见不得的操作时,被打断,想快速点开收藏该网页, 但是一直loading.

**Comment by newbe36524** [comment]
WOW，听起来不错

**Comment by newbe36524** [comment]
我想到了一个点子，反正搜索页面始终是展开的。

- 那就干脆在搜索页面弹框编辑好了。正好可以立即展开。
- 而且可以编辑玩之后实现自动且切换页签回来

妙呀。

**Comment by NMSAzulX** [comment]
妙呀~
